# Имя вашего workflow, которое будет отображаться в интерфейсе GitHub Actions
name: UI tests

# Указываем, когда будет запускаться данный workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Playwright tests with pytest and generate Allure results
        run: |
          pytest -m "authorization" --alluredir=allure-results --numprocesses 2

      # Восстанавливаем историю покрытия из кеша
      - name: Restore Coverage history
        uses: actions/cache/restore@v4
        with:
          path: coverage-history.json
          key: coverage-history-${{ github.run_id }}
          restore-keys: |
            coverage-history-

      # Генерируем HTML-отчет и обновляем историю
      - name: Generate Coverage report
        run: |
          ui-coverage-tool save-report

      # Сохраняем историю обратно в кеш
      - name: Cache Coverage  history
        if: always()
        uses: actions/cache/save@v4
        with:
          path: coverage-history.json
          key: coverage-history-${{ github.run_id }}

      # Загружаем HTML-отчет как артефакт
      - name: Upload Coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html

      # Сохраняем результаты тестов как артефакт для следующей джобы
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()  # Сохраняем даже если тесты упали
        with:
          name: allure-results
          path: allure-results

  publish-report:
    runs-on: ubuntu-latest
    needs: run-tests  # Эта джоба запустится ТОЛЬКО после завершения run-tests
    if: always()  # Запускаем даже если run-tests завершилась с ошибкой

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Загружаем сохранённые результаты тестов
      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          sudo tar -zxvf allure-2.24.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.24.0/bin/allure /usr/local/bin/allure
          allure --version
        if: always()

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-history --clean
        if: always()

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history